### PR TITLE
Add-hijri-date

### PR DESCRIPTION
**Pull request by rizkybaihaqy**
## What's this PR do ? ⭐️
- Create Hiji Date Component with working detail
- [classnames](https://github.com/JedWatson/classnames) packages for more readable class toggling

The api would be: 
```jsx
// children: number;
// event: string | undefined;
<HijriDate event="maulid">{10}</HijriDate>
```

## What are the relevant ticket ? ⭐️
https://gteam.atlassian.net/browse/MAIB-63

## Definition of Done:

-   [ ] Does this PR introduces a breaking change ?

-   [x] Does this PR passes Lint locally ?

-   [ ] Does this PR requires Database changes ?

-   [ ] Does this PR requires a regression test by QA ?

-   [x] Does this PR adds new dependencies ? (network setup, new 3rd party services)

## Screenshots (if appropriate)
d

### CODE REVIEW

**Comment by hilmiwicak** [comment]
I'm unable to run dev
```
$ npm run dev
> next-practivce@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Error: An unknown PostCSS plugin was provided ([object Object]).
Read more: https://nextjs.org/docs/messages/postcss-shape
/home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:158
            throw new Error(genericErrorText);
                  ^

Error: Malformed PostCSS Configuration
    at /home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:158:19
    at Array.forEach (<anonymous>)
    at Object.getPostCssPlugins (/home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:129:13)
    at async /home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/index.js:99:36
    at async Object.resolveUrlLoader (/home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js:25:26)
```

**Comment by rezzaldy** [comment]
I got same error like @hilmiwicak, but from the screenshot attachment its looks similar from the prototype, Fantastic!

**Comment by rizkybaihaqy** [comment]
> I'm unable to run dev
> 
> ```
> $ npm run dev
> > next-practivce@0.1.0 dev
> > next dev
> 
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> Error: An unknown PostCSS plugin was provided ([object Object]).
> Read more: https://nextjs.org/docs/messages/postcss-shape
> /home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:158
>             throw new Error(genericErrorText);
>                   ^
> 
> Error: Malformed PostCSS Configuration
>     at /home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:158:19
>     at Array.forEach (<anonymous>)
>     at Object.getPostCssPlugins (/home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:129:13)
>     at async /home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/config/blocks/css/index.js:99:36
>     at async Object.resolveUrlLoader (/home/wicak/gteam/maib/frontend/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js:25:26)
> ```

Will resolve after #2 got merged

**Review by aryakpt — APPROVED** [review]

**Review by rezzaldy — APPROVED** [review]
LGTM👌

**Pull request merged**
